version: '3'

services:
  web:
     image: cityenabler/cityfrontend:1.9.0
     ports:
       - "8081:8080"
     env_file:
       - be.env
       - fe.env
       - tools.env
       - idm.env
       - rabbit.env
     volumes:
       - webapps:/usr/local/tomcat/webapps
       - images:/images
       - /dev/urandom:/dev/random
     deploy:
       replicas: 1
       restart_policy:
         condition: any
         delay: 5s
         max_attempts: 3
         window: 120s

networks:
  default:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1400

volumes:
  webapps:
  images:
